### ISSUE TITLE
Extracting ICNARC physiological variables from EMAP

### ISSUE THREAD

**Issue by tagimoucia-cheryl** [datascibc/cheryl-phd#15]
- [x] EMAP access
- [x] review Aasiyah package variables
- [x] EPIC access
- [x] front end correlation with EPIC
- [x] Export files (with physiological variables) from EMAP 
- [ ] Create combined data frame in R containing ALL relevant variables

**Comment by tagimoucia-cheryl** [comment]
- [x] EMAP access
- [x] EPIC access
- [x] Front end correlation with EPIC

**Comment by docsteveharris** [comment]
physiology extracted; will kill this ticket now and see what the right next steps are
