### ISSUE TITLE
PhD registration 

### ISSUE THREAD

**Issue by tagimoucia-cheryl** [datascibc/cheryl-phd#2]
Registration steps for PhD

- [x] steve needs to get primary supervisor status
- [x] cheryl to then do paper work
- [x] dw to be 2ndry

**Comment by tagimoucia-cheryl** [comment]
Have emailed PG student registration to ask for best route/which web form etc, and also emailed DW.
Waiting to hear back from both parties

**Comment by docsteveharris** [comment]
Cheryl struggling to find how to register; will write an email which I will forward on to IHI to find this

**Comment by tagimoucia-cheryl** [comment]
Managed to find side access to get to a list that includes IHI. 

Will proceed now.
