### ISSUE TITLE
ICNARC on EMAP prep

### ISSUE THREAD

**Issue by tagimoucia-cheryl** [datascibc/cheryl-phd#23]
- [x] SH to please review [Cheryl's new emap-icnarc repo](https://github.com/tagimoucia-cheryl/emap_icnarc)
- [x] touch base on wed 11/8/21

**Comment by docsteveharris** [comment]
we probably need to go through this again.
quick thoughts
- nice/tidy/clean!
- use file extensions e.g .sql 
- drop the license; nothing to do with me! this is your work
- find a single patient and work though using the front end as reference to check that your code is behaving as expected. this is going to give you confidence that the work is the quality you want
