### ISSUE TITLE
Get a copy of the existing ICNARC physiology code that runs against Clarity/Caboodle

### ISSUE THREAD

**Issue by docsteveharris** [datascibc/cheryl-phd#25]
Speak to Jon G
The code he has will prepare the highest/lowest etc.
You may not want to do all of that in SQL but instead bring in the raw physiology and then transform in R _but_ it will be useful to see what he's done.
He also will be pulling from Caboodle/Clarity where as you're working from EMAP so again this is for reference rather than to actually use.

**Comment by tagimoucia-cheryl** [comment]
CA emailed JG 12/8/21 - will go back to further working and isolating ICNARC variables when hear from him to ensure am using correct variables to filter
